services:
  cpp-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: matching-server
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=gamedata
    depends_on:
      - postgres
    networks:
      - sockets-network
    restart: unless-stopped
  
  postgres:
    image: postgres:14
    container_name: postgres-db
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=gamedata
    volumes:
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql # For initialization scripts
      - ./postgres-data:/var/lib/postgresql/data # Bind mount for persistent data
    networks:
      - sockets-network
    restart: unless-stopped

networks:
  sockets-network:
    driver: bridge