spring.application.name: logging

kafka:
  url: kraft-cluster-kafka-bootstrap.kafka.svc:9092
server:
  port: 8001
feign:
  indicator-service:
     url: indicator-service-app.indicator.svc.cluster.local:8085
