name: Simple MatchingServer CI/CD

on:
  push:
    branches: [ main, dev ]
    paths:
      - 'MatchingServer/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: 캐시 로드
        uses: actions/cache@v3
        with:
          path: |
            MatchingServer/build
            MatchingServer/vcpkg_installed
          key: ${{ runner.os }}-build-${{ hashFiles('MatchingServer/vcpkg.json', 'MatchingServer/Makefile', 'MatchingServer/src/**/*.cpp', 'MatchingServer/src/**/*.h') }}
          restore-keys: |
            ${{ runner.os }}-build-
      
      - name: vcpkg 캐시
        uses: actions/cache@v3
        with:
          path: |
            MatchingServer/vcpkg
            MatchingServer/vcpkg_installed
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('MatchingServer/vcpkg.json') }}

  deploy:
    needs: build  # build 작업 이후에 실행
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      
      - name: 서버 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ${{ secrets.DEV_SERVER_USER }}
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          port: ${{ secrets.DEV_SSH_PORT }}
          script: |
            # 레포지토리 루트 디렉토리로 이동
            cd ${{ secrets.DEV_DEPLOY_PATH }}/../
            
            # 현재 브랜치 확인 및 pull
            CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
            echo "Current branch: $CURRENT_BRANCH"
            
            # 로컬 변경사항 저장 (있는 경우)
            git stash
            
            # main 또는 dev 브랜치에서 최신 코드 가져오기
            if [ "$CURRENT_BRANCH" != "main" ] && [ "$CURRENT_BRANCH" != "dev" ]; then
              echo "Checking out dev branch..."
              git checkout dev
            fi
            
            # 최신 코드 가져오기
            git pull origin $CURRENT_BRANCH
            
            # 변경 사항 확인
            if git diff --name-only HEAD@{1} HEAD | grep -q 'MatchingServer/'; then
              echo "변경 사항이 MatchingServer 디렉토리에서 감지되었습니다."
              
              # MatchingServer 디렉토리로 이동 후 빌드 스크립트 실행
              cd MatchingServer
              chmod +x build.sh
              ./build.sh
            else
              echo "MatchingServer 디렉토리에 변경 사항이 없습니다."
            fi